### ISSUE TITLE
Add corpus documentation

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#991]
Several corpora don't have documentation file, or the documentation is too sparse. We should include proper documentation for the following corpora:

- [ ] Dutch Annual reports
- [ ] KB krantencorpus
- [x] Eighteenth Century Collections Online (closed by #1270)
- [x] Guardian-Observer (closed by #1270)
- [ ] Jewish Funerary Inscriptions
- [x] Troonredes (closed by #1167)
- [x] Rechtspraak (closed by #1166)
- [x] Finnish parliamentary corpus (update needed; closed by #1279)

**Comment by lukavdplas** [comment]
Note: Dutch Annual reports also needs documentation for the word models.
