### ISSUE TITLE
Show and filter corpus metadata in index

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#994]
As we add more corpora, the current corpus overview will likely become cumbersome.

- [x] Update to a more compact view that displays more metadata of the corpus. For example, we could show the time period and the language(s), and the type of data (newspaper, funerary inscriptions, etc.) -> resolved by #1142
- [x] Add the option to filter the metadata. -> closed by #1142 
- [ ] The corpus dropdown in the navbar at the top should just be a link to the index, or replaced with a dropdown of bookmarked corpora (c.f. #1102 )
